/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "Combat Log": "战斗日志",
    "Dao (Locked)": "道 (未解锁)",
    "Stat Allocation": "属性分配",
    "Resume": "返回",
    "Tutorial • Floor": "教程 • 层数",
    "Floor": "层数",
    "Continue": "继续",
    "Patch Notes - v": "更新日志 - v",
    "Reset Save": "重置存档",
    "Plane (???)": "位面 (???)",
    "Allocate:": "分配:",
    "Awakening the Dao…": "觉醒之道...",
    "Consolidate Insights": "巩固洞察力",
    "Auto progression": "自动推进",
    "Fixes": "修复",
    "Highlights": "高亮",
    "HP": "生命值",
    "Idle Xanxia v": "放置仙侠 v",
    "Improved stat descriptions": "改进属性描述",
    "Current Path": "当前路径",
    "Offline Gains": "离线收益",
    "Precision": "精准",
    "The Dao never sleeps, neither do you.": "道永不停息，你亦是如此。",
    "The Path of the Immortal": "不朽之路",
    "Up Next": "Up Next",
    "Vitality": "活力",
    "Aspect Awakened": "天赋觉醒",
    "You have accumulated Insight, keep pushing yourself!": "你已经积累了洞察力，继续努力前行吧！",
    "You have defeated": "你击败了",
    "none": "无",
    "essences:": "精华:",
    "Inner Self": "内在自我",
    "Meditate": "冥想",
    "Might": "实力",
    "Slime": "史莱姆",
    "Rebirth (???)": "重生 (???)",
    "Not consolidated:": "未巩固:",
    "Resilience": "韧性",
    "Swiftness": "敏捷",
    "to the next breakthrough": "迈向下一个突破",
    "No battles were credited.": "暂无战斗记录。",
    "Insights - The understanding you gain through battle and reflection. Consolidate Insights to advance your cultivation.": "洞察力 - 你通过战斗和反思获得的理解。将洞察力加以巩固，以促进你的修炼进程。",
    "Insights": "洞察力",
    "First Insight": "第一次洞察",
    "Cultivation Begins": "修炼开始了",
    "Enough. \n\n The essence you have gathered has taken form. \n\n Look inside yourself.": "足够了。\n\n你收集到的精华已经成形。\n\n 请审视自己的内心。",
    "Cultivation": "修炼",
    "Consolidate your insights": "巩固你的洞察",
    "Consolidate": "巩固",
    "Active:": "激活:",
    "Armor": "护甲",
    "Armor Penetration": "护甲穿透",
    "Aspect of the Slime": "史莱姆天赋",
    "A journey of a thousand li begins with a single step. Here I am!": "千里之行，始于足下。我来了！",
    "Attack Interval": "攻击间隔",
    "Explore the forest": "探索森林",
    "Start Your Adventure": "开始你的冒险",
    "Welcome": "欢迎",
    "enemies.": "敌人.",
    "From those battles, you have collected": "从这些战斗中，你收集了",
    "Advance to Floor": "冒险到层数",
    "Pause": "暂停",
    "Chakras": "经脉",
    "Body Foundation": "身体基础",
    "Back to Combat": "返回到战斗",
    "Damage": "伤害",
    "Common": "普通",
    "Rare": "稀有",
    "Legendary": "传说",
    "Uncommon": "罕见",
    "A frog in a well.": "井底之蛙。",
    "A toad wanting to eat swan meat.": "一只蟾蜍想吃天鹅肉。",
    "Cripple your own cultivation and save me some time.": "自毁自己的修炼过程，为我节省些时间。",
    "Do you even know who my father is?": "你到底知不知道我父亲是谁？",
    "Do you ever wonder what swan meat tastes like?": "你有没有想过天鹅肉是什么味道？",
    "Heaven is quiet today.": "今天天堂很安静。",
    "Hmph! Arrogant!": "哼！傲慢！",
    "I, your father, have eaten more salt than you have eaten rice!": "作为你的父亲，我吃的盐比你吃的米饭还多！",
    "I'll give you some face, cripple your own cultivation and crawl away.": "我要让你难堪，毁掉你的修炼过程，然后爬走。",
    "In my youth, servants stronger than you fetched my tea.": "在我年轻的时候，比你更强壮的仆人给我端茶。",
    "Junior, you dare?!": "小弟，你敢吗？",
    "Kowtow three times and I might leave your corpse intact.": "磕头三次，我或许能让你的尸体完好无损。",
    "Seriously though, do you know who my father is? I was abandoned when I was little...": "不过说真的，你知道我父亲是谁吗？我小时候被遗弃了……",
    "Striking a stone with an egg.": "用鸡蛋敲石头。",
    "The gap between us is like heaven and earth.": "我们之间的差距就像天与地。",
    "Wait - that was my last life-saving treasure.": "等等——那是我最后的救命宝物。",
    "You are but a speck of dust dreaming it is a mountain.": "你不过是一粒尘埃，却妄想自己是一座山。",
    "You are courting death!": "你在走向死亡！",
    "You are not qualified to speak in my presence.": "你没有资格在我面前说话。",
    "You cultivate like a blind man painting.": "你修炼得像个盲人作画。",
    "You have eyes but cannot see Mt. Tai.": "你有眼睛却看不到泰山。",
    "You overestimate yourself.": "你自视过高。",
    "Your cultivation is shallow, but your arrogance is deep.": "你的修为浅薄，但你的傲慢却很深。",
    "Your existence offends my eyes.": "你的存在冒犯了我的眼睛。",
    "Your family tree should have ended at the root.": "你的家族谱应该在根部就终止了。",
    "Miss": "未命中",
    "Awakened (": "觉醒 (",
    "Effects": "效果",
    "Dodge": "闪避",
    "Equipped (": "已装备 (",
    "Tier": "层级",
    "Regen per second": "回复每秒",
    "Loadingâ€¦": "加载中¦",
    "In Progress (": "进行中 (",
    "Hit Point": "命中点",
    "Hit Chance": "命中率",
    "Foundation": "基础",
    "Essence Assimilation": "精华同化",
    "Damage Mitigation": "伤害减免",
    "Awakened Aspects": "觉醒天赋",
    "Critical Chance": "暴击几率",
    "All awakened Aspects are equipped.": "所有觉醒的天赋都已装备。",
    "Confirm Reset": "确认重置",
    "Are you sure you want to reset the game, All progress will be lost": "你确定要重置游戏吗？届时所有进度都将丢失。",
    "A Master's Warning": "一位大师的告诫",
    "Return to the Woods": "返回到森林",
    "Temper yourself": "磨练自己",
    "You're not ready for this beast yet.\n\n Go back in the woods, find an enemy you want to learn from and use my amulet to collect their essence.": "你目前还不具备面对这个怪物的条件。\n\n回到森林里去吧，找一个你想要学习的敌人，然后用我的护身符来收集他们的灵魂精华。",
    "Bunnycorn": "玉米兔",
    "Wolf": "狼",
    "None.": "无.",
    "Equipped Aspects": "已装备天赋",
    "Active Effects": "激活效果",
    "Aspects": "天赋",
    "Elite": "精英",
    "Aspect of the Forest Wolf": "森林狼天赋",
    "Aspects In Progress": "进行中的天赋",
    "No Aspects equipped.": "暂未装备天赋。",
    "Attribute Cultivation": "属性培养",
    "Aspect": "天赋",
    "Awakened": "已觉醒",
    "Assimilation": "吸收",
    "Body": "身体",
    "Dao (locked)": "道 (未解锁)",
    "Equipped": "已装备",
    "MAX": "最大",
    "In Progress": "进行中",
    "Forest Wolf": "森林狼",
    "Acupoint Awakening": "穴位激活",
    "Major Realm Completion": "主要境界达成",
    "Mortal Realm": "凡人境界",
    "Your blows find both flesh and weakness.": "你的攻击既能击中肉体，也能击中弱点。",
    "A toad dreaming of swan meat.": "一只梦想着能吃到天鹅肉的癞蛤蟆。",
    "I'll give you some face: cripple your own cultivation and crawl away.": "我这就给你个教训：毁掉你自己的修行，然后滚蛋吧。",
    "The weight behind every strike.": "每一次打击背后都蕴含着沉重的分量。",
    "Wait, that was my last life-saving treasure.": "等等，那可是我最后的救命之物了。",
    "You move like the wind and strike like lightning.": "你的行动如风般敏捷，出手如电般迅猛。",
    "Analytical": "分析",
    "Plane (Locked)": "位面 (未解锁)",
    "View:": "视图:",
    "Your life force flows deep and unbroken.": "你的生命力深厚且坚韧不摧。",
    "Who are you?": "你是谁?",
    "time)": "次)",
    "FIRE": "火",
    "Equip any Dao": "装备任意道",
    "Choose your Dao": "选择你的道",
    "BLOOD": "血液",
    "FIST": "拳头",
    "Practice your Dao": "修炼你的道",
    "BODY": "身体",
    "LIGHTNING": "雷电",
    "SHADOW": "暗影",
    "In the darkness of your soul, you feel something calling to you...": "在你内心深处的黑暗之中，你感觉到有一种力量在召唤着你……",
    "Seek for other Truths (": "去探寻其他的真理吧（",
    "Something stirs inside of you...": "内心深处有某种东西在蠢蠢欲动……",
    "The pressure grows in your soul...": "灵魂中的压力不断增大……",
    "Without ever seeing your enemy, a force beyond your understanding strikes your chest.": "在从未见过敌人的情况下，一股超乎你理解的力量击中了你的胸膛。",
    "Your breath stops. Your heart falters. Your consciousness unravels.": "你的呼吸停止了。你的心脏停止了跳动。你的意识开始瓦解。",
    "SWORD": "剑",
    "LIGHT": "光",
    "EARTH": "土",
    "BEAST": "野兽",
    "METAL": "金属",
    "WIND": "铁",
    "ICE": "冰",
    "— choose your path": "— 选择你的道路",
    "Adds +8 flat physical damage and +15% physical damage to every strike.": "增加8点固定物理伤害，每次攻击额外提升15%物理伤害。",
    "ASHEN TEMPEST": "灰烬风暴",
    "Back to Daos": "返回重选",
    "BLAZING FIST": "炽烈拳",
    "BURNING HEART": "焚心",
    "COLD CURSE": "寒冰诅咒",
    "CRIMSON FEAST": "血色盛宴",
    "Each hit bleeds for 10% of hit damage/s for 3s. Max 12 stacks. Each stack slows enemy AS by 3% (cap 36%).": "每次攻击造成流血效果，每秒造成本次攻击伤害的10%，持续3秒，最大叠加12层。每层叠加降低敌人3%攻击速度（上限36%）。",
    "Each hit reduces enemy healing by 25% for 4s. Refreshes on hit. Floor: 10%.": "每次攻击使敌人治疗效果降低25%，持续4秒，攻击时刷新效果，最低降低10%。",
    "Every 5 hits freezes the enemy for 1.25s. +15% damage while frozen. 6s immunity after.": "每5次攻击冻结敌人1.25秒，敌人被冻结时自身伤害提升15%，冻结后获得6秒免疫。",
    "Gain 1 stack per 5% HP lost. +1% damage per stack. Max 10 stacks (10%). Refreshes on damage taken.": "每损失5%生命值获得1层叠加，每层叠加增加1%伤害，最大10层（10%），受到伤害时刷新叠加。",
    "Grants +4% crit chance and +0.10x crit multiplier.": "增加4%暴击几率，提升0.10倍暴击伤害倍率。",
    "Heals for 3% of damage dealt. Capped at 2% of max HP per hit.": "恢复本次造成伤害的3%生命值，单次攻击治疗上限为最大生命值的2%。",
    "HEMORRHAGE": "出血",
    "ICE MIRROR": "寒冰镜像",
    "Reflects 12% of damage taken back to attacker. Capped at 2% of your max HP per hit.": "将12%所受伤害反弹给攻击者，单次攻击反弹上限为自身最大生命值的2%。",
    "SANGUINE PACT": "血色契约",
    "WINTYR’S SILENCE": "温蒂尔的缄默",
    "35% chance on hit to reduce enemy attack speed by 28% for 2s. 4s cooldown.": "攻击时有35%概率降低敌人28%攻击速度，持续2秒。冷却时间4秒。",
    "BATTLEFIELD": "战场",
    "Constantly poisons all enemies for 5 flat damage per second.": "持续对所有敌人施加毒素，每秒造成5点固定伤害。",
    "DISSECTION": "解剖",
    "Each hit applies a poison dealing 4 flat damage per second for 6s. Max 12 stacks.": "每次攻击施加毒素，每秒造成4点固定伤害，持续6秒，最大叠加12层。",
    "Each hit deals 12% AoE damage to other enemies and applies a 3 flat DPS bleed for 2s.": "每次攻击对其他敌人造成12%范围伤害，并施加持续2秒、每秒3点固定伤害的流血效果。",
    "Each hit deals 15% AoE damage to other enemies and slows their attack speed by 6% for 2s.": "每次攻击对其他敌人造成15%范围伤害，并使其攻击速度降低6%，持续2秒。",
    "Each hit deals 5 bonus true damage that ignores all armor.": "每次攻击额外造成5点无视所有护甲的真实伤害。",
    "Each hit grants +1% attack speed for 5s. Max 8 stacks (8%). Stacks decay individually.": "每次攻击获得1%攻击速度，持续5秒，最大叠加8层（8%），每层独立衰减。",
    "EDGECRAFT": "工艺",
    "FLOWSTATE": "流态",
    "Grants +5% dodge chance.": "获得5%闪避几率。",
    "LEAF ON THE WIND": "风中落叶",
    "POISON": "毒",
    "ROTTING MIASMA": "腐烂瘴气",
    "VENOM FANG": "毒牙",
    "When hit, poisons the attacker for 8 flat damage per second for 4s. Max 8 stacks.": "受到攻击时，对攻击者施加毒素，每秒造成8点固定伤害，持续4秒，最大叠加8层。",
    "WIND BLADE": "风刃",
    "WITHERING BLIGHT": "枯萎疫病",
    "STORM": "风暴",
    "10% chance enemies hit each other instead. Grants +5% dodge.": "10%概率使敌人互相攻击，自身获得5%闪避。",
    "10% chance that enemy attacks hit another enemy instead of you.": "10%概率敌人的攻击会命中另一名敌人，而非你。",
    "Attacks from Veil deal +12% bonus damage.": "来自暗影帷幕的攻击造成额外12%伤害。",
    "Aura: all enemies deal 5% less damage and have 5% reduced hit chance.": "光环：所有敌人造成的伤害降低5%，命中几率降低5%。",
    "Become invulnerable for 1s every 12s.": "每12秒获得1秒无敌效果。",
    "DARK AMBUSH": "暗影伏击",
    "Deals 5 flat damage to all enemies every 2s. Damage doubles every 2s.": "每2秒对所有敌人造成5点固定伤害，且每2秒伤害翻倍。",
    "EYE OF THE STORM": "风暴之眼",
    "ROAR": "咆哮",
    "SCATTER": "散射",
    "UMBRAL DECEIT": "影雾欺诈",
    "VEIL": "暗影帷幕",
    "Embrace the Dao": "悟彻大道",
    "Every step forward will shape you—and be shaped by you.": "每一步前行，皆塑造你我，亦为你我所塑造。",
    "Once you embark on this path, there is no turning back.": "此途既启，再无归途。",
    "Return": "返回",
    "Your fate entwines with the Dao.": "汝之宿命，与大道相融。",
    "ADAPT": "适应",
    "Each kill grants a permanent +1% damage stack until death. Max 10 stacks (10%).": "每次击杀获得永久+1%伤害加成，最多叠加10层（10%），死亡后重置。",
    "FERAL RAGE": "野性怒火",
    "Gains 1 stack/s (max 10, 3s each). Each stack copies 10% of enemy's top stat as a counter-bonus.": "每秒获得1层（最多10层，每层持续3秒）。每层复制敌人最高属性的10%作为额外加成。",
    "Gains up to +15% crit chance and +0.10x crit damage scaling with missing HP.": "根据损失生命值，最多获得+15%暴击率与+0.10倍暴击伤害。",
    "Grants +3 flat HP regen per tick and +10% healing received.": "每回合恢复3点固定生命值，受到治疗效果+10%。",
    "HARDEN": "硬化",
    "POUNCE": "猛扑",
    "REGENERATE": "再生",
    "Stuns the enemy for 1s at the start of combat. Deals 100% bonus damage on the opening hit.": "战斗开始时使敌人眩晕1秒。首次攻击造成100%额外伤害。",
    "TEMPER": "淬炼",
    "When a hit exceeds 10% of your max HP, reduce that hit by 15%. Cap: 20 damage absorbed.": "当单次伤害超过你最大生命值的10%时，减免该次伤害15%。最高减免20点伤害。",
    "BASTION": "堡垒",
    "Each hit applies a bleed dealing 4 flat damage per second for 3s. Max 1 stack.": "每次攻击施加流血效果，每秒造成4点固定伤害，持续3秒，最多叠加1层。",
    "Each hit grants +2% damage for 2s. Max 5 stacks (10%). All stacks refresh on hit.": "每次攻击获得+2%伤害，持续2秒，最多叠加5层（10%），攻击时刷新所有层数。",
    "Each hit reduces enemy attack speed by 8% and dodge by 5% for 3s. Refreshes on hit.": "每次攻击降低敌人8%攻击速度与5%闪避，持续3秒，攻击时刷新。",
    "Each hit reduces enemy END by 5% and armor by 3 for 3s. Refreshes on hit.": "每次攻击降低敌人5%耐力与3点护甲，持续3秒，攻击时刷新。",
    "ENDURING CRAG": "持久峭壁",
    "ENTANGLE": "纠缠",
    "FLURRY": "疾风",
    "Generates 1 stack every 4s (max 5, permanent until combat ends). Each stack grants +1% max HP.": "每4秒获得1层（最多5层，战斗中永久保留），每层增加+1%最大生命值。",
    "Generates a shield that absorbs 1 hit every 5s.": "每5秒生成一个护盾，可抵挡1次攻击。",
    "Grants +6% flat damage reduction.": "获得+6%固定伤害减免。",
    "IMPACT": "冲击",
    "INTERNAL SHOCK": "内震",
    "Reduces crit damage taken by 10%, CC duration by 10%, and DoT effects by 10%.": "受到的暴击伤害降低10%，控制效果持续时间降低10%，持续伤害效果降低10%。",
    "STONEHEART": "石之心",
    "THORNBOUND": "荆棘束缚",
    "VERDANT GROWTH": "翠绿生长",
    "When hit, deals 15 flat retaliation damage to the attacker.": "受到攻击时，对攻击者造成15点固定反击伤害。",
    "WOOD": "木",
    "Each hit reduces enemy END by 3% and armor by 2 for 8s. Max 5 stacks.": "每次攻击降低敌人3%耐力与2点护甲，持续8秒。最多叠加5层。",
    "Each hit taken grants a stack of +2.5% DR for 5s. Max 6 stacks (15% DR).": "每次受到攻击获得一层伤害减免效果，持续5秒。最多叠加6层（15%伤害减免）。",
    "Each hit taken grants a stack of +3% damage for 5s. Max 6 stacks (18% damage).": "每次受到攻击获得一层伤害加成效果，持续5秒。最多叠加6层（18%伤害加成）。",
    "HARDENING": "强化",
    "SMELTED CORE": "熔炼核心",
    "TEMPERING": "淬炼",
    "5% chance on hit to stun the enemy for 0.6s. 4.5s immunity after.": "攻击时有5%概率使敌人眩晕0.6秒，之后获得4.5秒免疫。",
    "CHAINBREAKER": "破链者",
    "Each hit deals 10% AoE damage to other enemies with 8% chance to stun them for 0.3s. 3s immunity.": "每次攻击对其他敌人造成10%范围伤害，并附带8%概率使其眩晕0.3秒，获得3秒免疫。",
    "Reduces attack interval by 40ms.": "攻击间隔缩短40毫秒。",
    "STORM’S GRASP": "风暴之握",
    "THUNDER RUSH": "雷霆突袭",
    "Embrace Rebirth": "浴火重生",
    "Fire Dao — Ashen Tempest": "火之道 —— 灰烬风暴",
    "Reach Floor 32 to unlock Rebirth": "到达 32 层即可解锁“重生”功能",
    "Dao": "道",
    "Ash burns from whithin": "灰烬从内部燃烧",
    "Before your tempered will, enemy strikes lose their strength.": "在你坚韧的意志面前，敌人的攻势便失去了威力。",
    "Dao Resonance": "道之共鸣",
    "Practice the Dao": "修道",
    "You have grown": "你成长了",
    "What once stood as a mountain before you is now just a pebble on the road.\n\nShow me how far you can walk.": "曾经矗立在你面前的那座山，如今不过是一块路边的鹅卵石罢了。\n\n告诉我你能走多远。",
    "Advance": "前进",
    "I am afraid you will not be able to advance much further with your current body.\n\nIt is time for you to learn about rebirth.": "恐怕以你现在的身体状况，再无法取得更大的进步了。\n\n是时候让你了解重生的事宜了。",
    "Thornback": "棘背",
    "Your body has reached its limit": "你的身体已经达到了极限。",
    "Rebirth": "重生",
    "Perform Rebirth": "执行重生",
    "Back": "返回",
    "All Aspects": "所有天赋",
    "Ready": "就绪",
    "progress": "进度",
    "Rebirth Milestones": "重生里程碑",
    "Base stats": "基础属性",
    "Memories": "记忆",
    "Carries Forward": "承前启后",
    "Conquered floors will deepen your Dao once more": "已攻克的层数将再次深化你的道途",
    "Dao path & Progress": "道途与进度",
    "Essence collected": "已收集精华",
    "New Ascent": "新的转生",
    "Reach Floor 32 this life": "此生抵达第32层",
    "Rebirth Readiness": "重生就绪",
    "Reforged Anew": "焕然重铸",
    "Strengthen the Soul or the Body": "强化灵魂 或 强化体魄",
    "Transcend this life - Claim the next": "超脱此生——迈向下一境",
    "Aspect Slots +1": "天赋栏位 +1",
    "Body Cultivations:": "肉身修炼：",
    "Body Strengthening": "肉身强化",
    "Choose your strengthening path": "选择强化路线",
    "Confirm Choice": "确认选择",
    "Expand the inner self and contain one more Aspect.": "拓展内在，多容纳一个道途。",
    "Increase stat per level": "提升每级属性",
    "or refine the Body.": "或淬炼肉身。",
    "Soul Cultivations:": "灵魂修炼：",
    "Soul Strengthening": "灵魂强化",
    "Temper the vessel so each future level grants greater strength.": "淬炼载体，使未来每一级都能获得更强力量。",
    "Upon rebirth, your foundation may temper the Soul": "重生后，你的根基可淬炼灵魂。",
    "Reforming Body in...": "身体改造中...",
    "Reforming Body...": "身体改造...",
    "The path of cultivation is paved with quiet failures.": "修行的道路是由无声的失败铺成的。",
    "Your body could not withstand the trial -- yet your will endures.": "你的身体无法承受这次考验——但你的意志却依然坚强。",
    "— UNLOCKED STORM_CROWNED_HAWK (Tier 1)": "— 已解锁 风暴加冕鹰天赋 (层级 1)",
    "— UNLOCKED ASPECT_GROVE_SERPENT (Tier 1)": "— 已解锁 格罗夫蛇天赋 (层级 1)",
    "Grove Serpent": "格罗夫蛇",
    "Thornback Boar": "棘背野猪",
    "First breakthrough": "首次突破",
    "Defeat the Floor 100 Guardian": "击败100层守护者",
    "Insight": "洞察",
    "With each battle, understanding gathers.\n\nWhen insight deepens, it must be consolidated.\n\nFocus your growth. Refine your strengths.": "每经历一场战斗，我们的理解都会加深。\n\n当洞察力加深时，必须加以巩固。\n\n专注于你的成长。磨砺你的优势。",
    "Complete all checklist milestones to proceed": "完成所有检查表中的里程碑才能继续",
    "Ancient Treant Sapling": "古代树人树苗",
    "StormCrownedHawk": "风暴加冕鹰",
    "A rare auction is being held in the upper realms.\n\nYou would learn much there... if only your cultivation were not so shallow.": "上方神界正在举办一场稀有拍卖会。你能在那里收获良多……只可惜你的修为尚且浅薄。",
    "Away for a while": "暂离片刻",
    "Break. Reform. Become.": "破碎，重塑，新生。",
    "failed src:": "加载资源失败：",
    "Heaven rewards perseverance.": "天道酬勤。",
    "Keep tempering yourself": "继续淬炼自身",
    "Missing art:": "缺失功法：",
    "The Path": "道途",
    "To fall is to learn.": "跌倒即是学习。",
    "You have done well. Keep pushing yourself. From here on, you walk alone until you leave this plane.\n\nRemember what I taught you. Strength without clarity is ruin.": "你做得很好，继续向前。从这里开始，你将独自前行，直至离开这个位面。记住我教你的一切。力量若没有心智的清明，只会带来毁灭。",
    "Moon-Touched Stag": "月照鹿",
    "Storm-Crowned Hawk": "风暴加冕鹰",
    "Tortoise": "乌龟",
    "No loot was collected from those battles.": "从这些战斗中没有收集到任何战利品。",
    "Dire Bear": "恐熊",
    "You have tempered your will against the Guardian of this Plane.\n\nThis world has given you all it can.\n\nBeyond it lie deeper laws.\nStronger storms.\nSharper truths.\n\nIf you are prepared to walk further, come with me.\nRemain if you must. When your resolve settles, crush this talisman. The path will open.": "你已经与这个位面的守护者进行了意志上的较量。\n\n这个世界已经给予了你所能给予的一切。\n\n在其之外，是更为深邃的法则。\n更猛烈的风暴。\n更清晰的真相。\n\n如果你愿意继续前行，就跟我来吧。\n如果你愿意留下，那就留下吧。当你的决心稳定下来时，就粉碎这个护身符。道路将会敞开。",
    "I am the boundary of this world.\n\nYour foundation will be tested now.": "我是这个世界的界限。\n\n你的根基此刻将受到考验。",
    "Plane Guardian": "位面守护者",
    "Plane": "位面",
    "100 cleared": "100 已清理",
    "...Passable": "...通行",
    "Ascend Beyond This Plane": "超脱此界",
    "At the World’s Limit": "世界之限",
    "Beyond This Sky": "天际之外",
    "Face the forest fury!": "直面森林之怒！",
    "Prepare yourself": "做好准备",
    "Prove yourself": "证明自我",
    "Temper Yourself Further": "进一步淬炼自身",
    "The Forest protects me": "森林守护着我",
    "Hidden Dragon": "潜龙",
    "The Ascendant Realm": "转生之境",
    "The Verdant Expanse": "苍莽旷野",
    "Travel": "旅行",
    "Void Pavillon": "虚空亭阁",
    "Cross the Void": "穿越虚空",
    "Stay": "留下",
    "Do you want to cross the void and travel to": "你想要穿越虚空并旅行到",
    "Blocked": "格挡",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "(T": "(T",
    "Mortal Realm • Skin Tempering — 1st Stage": "凡人界 • 皮肤强化 — 第 1 阶段",
    "Mortal Realm • Skin Tempering — 2nd Stage": "凡人界 • 皮肤强化 — 第 2 阶段",
    "Mortal Realm • Skin Tempering — 3rd Stage": "凡人界 • 皮肤强化 — 第 3 阶段",
    "Mortal Realm - Skin Tempering - 1st Stage": "凡人界 - 皮肤强化 — 第 1 阶段",
    "Mortal Realm - Skin Tempering - 2nd Stage": "凡人界 - 皮肤强化 — 第 2 阶段",
    "Mortal Realm - Skin Tempering - 3rd Stage": "凡人界 - 皮肤强化 — 第 3 阶段",
    "Mortal Realm • Flesh Remodeling — 1st Stage": "凡人界 • 肉体重塑 — 第 1 阶段",
    "Mortal Realm • Flesh Remodeling — 2nd Stage": "凡人界 • 肉体重塑 — 第 2 阶段",
    "Mortal Realm • Flesh Remodeling — 3rd Stage": "凡人界 • 肉体重塑 — 第 3 阶段",
    "Mortal Realm • Tendon Strengthening — 1st Stage": "凡人界 • 肌腱强化 — 第 1 阶段",
    "Mortal Realm • Tendon Strengthening — 2nd Stage": "凡人界 • 肌腱强化 — 第 2 阶段",
    "Mortal Realm • Tendon Strengthening — 3rd Stage": "凡人界 • 肌腱强化 — 第 3 阶段",
    "Mortal Realm • Bone Forging — 1st Stage": "凡人界 • 锻骨 — 第 1 阶段",
    "Mortal Realm • Bone Forging — 2nd Stage": "凡人界 • 锻骨 — 第 2 阶段",
    "Mortal Realm • Bone Forging — 3rd Stage": "凡人界 • 锻骨 — 第 3 阶段",
    "Reach Mortal Realm • Bone Forging — 1st Stage": "达到 凡人界 • 锻骨 — 第 1 阶段",
    "Reach Mortal Realm • Bone Forging — 2nd Stage": "达到 凡人界 • 锻骨 — 第 2 阶段",
    "Reach Mortal Realm • Bone Forging — 3rd Stage": "达到 凡人界 • 锻骨 — 第 3 阶段",
    "Mortal Realm • Blood Refinement — 1st Stage": "凡人界 • 血脉淬炼 — 第 1 阶段",
    "Mortal Realm • Blood Refinement — 2nd Stage": "凡人界 • 血脉淬炼 — 第 2 阶段",
    "Mortal Realm • Blood Refinement — 3rd Stage": "凡人界 • 血脉淬炼 — 第 3 阶段",
    "Mortal Realm • Organ Fortification — 1st Stage": "凡人界 • 器官强化 — 第 1 阶段",
    "Mortal Realm • Organ Fortification — 2nd Stage": "凡人界 • 器官强化 — 第 2 阶段",
    "Mortal Realm • Organ Fortification — 3rd Stage": "凡人界 • 器官强化 — 第 3 阶段",
    "Mortal Realm - Organ Fortification - 1st Stage": "凡人界 - 器官强化 — 第 1 阶段",
    "Mortal Realm - Organ Fortification — 2nd Stage": "凡人界 - 器官强化 — 第 2 阶段",
    "Mortal Realm - Organ Fortification — 3rd Stage": "凡人界 - 器官强化 — 第 3 阶段",
    "Mortal Realm • Marrow Cleansing — 1st Stage": "凡人界 • 骨髓净化 — 第 1 阶段",
    "Mortal Realm • Marrow Cleansing — 2nd Stage": "凡人界 • 骨髓净化 — 第 2 阶段",
    "Mortal Realm • Marrow Cleansing — 3rd Stage": "凡人界 • 骨髓净化 — 第 3 阶段",
    "Mortal Realm - Marrow Cleansing - 1st Stage": "凡人界 - 骨髓净化 - 第 1 阶段",
    "Mortal Realm - Marrow Cleansing - 2nd Stage": "凡人界 - 骨髓净化 - 第 2 阶段",
    "Mortal Realm - Marrow Cleansing - 3rd Stage": "凡人界 - 骨髓净化 - 第 3 阶段",
    "Mortal Realm - Chakra Purification - 1st Stage": "凡人界 - 脉轮净化 - 第 1 阶段",
    "Mortal Realm - Chakra Purification - 2nd Stage": "凡人界 - 脉轮净化 - 第 2 阶段",
    "Mortal Realm - Chakra Purification - 3rd Stage": "凡人界 - 脉轮净化 - 第 3 阶段",
    "Mortal Realm • Chakra Purification - 1st Stage": "凡人界 • 脉轮净化 - 第 1 阶段",
    "Mortal Realm • Chakra Purification - 2nd Stage": "凡人界 • 脉轮净化 - 第 2 阶段",
    "Mortal Realm • Chakra Purification - 3rd Stage": "凡人界 • 脉轮净化 - 第 3 阶段",
    "Mortal Realm • Chakra Purification — 1st Stage": "凡人界 • 脉轮净化 — 第 1 阶段",
    "Mortal Realm • Chakra Purification — 2nd Stage": "凡人界 • 脉轮净化 — 第 2 阶段",
    "Mortal Realm • Chakra Purification — 3rd Stage": "凡人界 • 脉轮净化 — 第 3 阶段",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "✕": "✕",
    "(*)": "(*)",
    "✓": "✓",
    "→": "→",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "@": "@",
    "^": "^",
    "&": "&",
    "%": "%",
    "--": "--",
    "=": "=",
    "?": "?",
    "!": "!",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Floor ": "层数 ",
    "Explore the forest: ": "探索森林: ",
    "Organ Fortification": "器官强化",
    "Marrow Cleansing": "骨髓净化",
    "Blood Refinement": "血液净化",
    "Bone Forging": "骨骼锻造",
    "Chakra Purification": "脉轮净化",
    "Cultivation Realm": "修炼境界",
    "Flesh Remodeling": "肉体重塑",
    "Marrow Cleansing": "骨髓净化",
    "Skin Tempering": "皮肤淬炼",
    "Tendon Strengthening": "肌腱强化",
    "Inner Foundation": "内在根基",
    "Jade Body": "玉质身躯",
    "Gather Insight : ": "收集洞察: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(([\d\.]+), ([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^\@keyframes(.+)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Each hit applies a burn dealing (.+) of hit damage per second for (.+)s. Stacks infinitely.$/, '每次攻击施加灼烧效果，每秒造成本次攻击伤害的 $1，持续 $2 秒，可无限叠加。'],
    [/^Mortal Realm • Skin Tempering \— (.+)th Stage$/, '凡人界 • 皮肤强化 — 第 $1 阶段'],
    [/^Mortal Realm - Skin Tempering \— (.+)th Stage$/, '凡人界 - 皮肤强化 — 第 $1 阶段'],
    [/^Mortal Realm • Flesh Remodeling \— (.+)th Stage$/, '凡人界 • 肉体重塑 — 第 $1 阶段'],
    [/^Mortal Realm - Flesh Remodeling \— (.+)th Stage$/, '凡人界 - 肉体重塑 — 第 $1 阶段'],
    [/^Reach Mortal Realm • Flesh Remodeling \— (.+)th Stage$/, '达到 凡人界 • 肉体重塑 — 第 $1 阶段'],
    [/^Mortal Realm • Tendon Strengthening \— (.+)th Stage$/, '凡人界 • 肌腱强化 — 第 $1 阶段'],
    [/^Mortal Realm - Tendon Strengthening \— (.+)th Stage$/, '凡人界 - 肌腱强化 — 第 $1 阶段'],
    [/^Mortal Realm - Tendon Strengthening \— (.+)th Stage$/, '凡人界 - 肌腱强化 — 第 $1 阶段'],
    [/^Reach Mortal Realm • Tendon Strengthening \— (.+)th Stage$/, '达到 凡人界 • 肌腱强化 — 第 $1 阶段'],
    [/^Mortal Realm • Bone Forging \— (.+)th Stage$/, '凡人界 • 锻骨 — 第 $1 阶段'],
    [/^Reach Mortal Realm • Bone Forging \— (.+)th Stage$/, '达到 凡人界 • 锻骨 — 第 $1 阶段'],
    [/^Mortal Realm - Bone Forging \— (.+)th Stage$/, '凡人界 - 锻骨 — 第 $1 阶段'],
    [/^Mortal Realm • Blood Refinement \— (.+)th Stage$/, '凡人界 • 血脉淬炼 — 第 $1 阶段'],
    [/^Mortal Realm - Blood Refinement \— (.+)th Stage$/, '凡人界 - 血脉淬炼 — 第 $1 阶段'],
    [/^Mortal Realm • Organ Fortification \— (.+)th Stage$/, '凡人界 • 器官强化 — 第 $1 阶段'],
    [/^Mortal Realm - Organ Fortification \— (.+)th Stage$/, '凡人界 - 器官强化 — 第 $1 阶段'],
    [/^Mortal Realm - Marrow Cleansing \— (.+)th Stage$/, '凡人界 - 骨髓净化 — 第 $1 阶段'],
    [/^Mortal Realm • Marrow Cleansing \— (.+)th Stage$/, '凡人界 • 骨髓净化 — 第 $1 阶段'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^Attack Interval ([\d\.]+) sec$/, '攻击间隔 $1 秒'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.]+)\/sec$/, '+$1/秒'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^Crit Chance ([\d\.]+)\%$/, '暴击率 $1%'],
    [/^Hit Chance ([\d\.]+)\%$/, '命中率 $1%'],
    [/^Dodge Chance ([\d\.]+)\%$/, '闪避率 $1%'],
    [/^Damage Reduction ([\d\.]+)\%$/, '伤害减免 $1%'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) HP Regen$/, '+$1 生命值回复'],
    [/^\+([\d\.,]+) Physical Damage$/, '+$1 物理伤害'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Defeated Wolf \(\+([\d\.,]+) XP\)$/, '击败 狼 (+$1 经验值)'],
    [/^Defeated Ancient Treant Sapling \(\+([\d\.,]+) XP\)$/, '击败 古代树人树苗 (+$1 经验值)'],
    [/^Defeated StormCrownedHawk \(\+([\d\.,]+) XP\)$/, '击败 风暴加冕鹰 (+$1 经验值)'],
    [/^Defeated Bunnycorn \(\+([\d\.,]+) XP\)$/, '击败 玉米兔 (+$1 经验值)'],
    [/^Defeated GroveSerpent \(\+([\d\.,]+) XP\)$/, '击败 格罗夫蛇 (+$1 经验值)'],
    [/^Defeated Moon-Touched Stag \(\+([\d\.,]+) XP\)$/, '击败 月照鹿 (+$1 经验值)'],
    [/^Defeated Tortoise \(\+([\d\.,]+) XP\)$/, '击败 乌龟 (+$1 经验值)'],
    [/^Defeated Dire Bear \(\+([\d\.,]+) XP\)$/, '击败 恐熊 (+$1 经验值)'],
    [/^Defeated Plane Guardian \(\+([\d\.,]+) XP\)$/, '击败 位面守护者 (+$1 经验值)'],
    [/^Defeated Vagabond \(\+([\d\.,]+) XP\)$/, '击败 流浪者 (+$1 经验值)'],
    [/^Defeated Slime \(\+([\d\.,]+) XP\)$/, '击败 史莱姆 (+$1 经验值)'],
    [/^Defeated Thornback \(\+([\d\.,]+) XP\)$/, '击败 棘背 (+$1 经验值)'],
    [/^Essence \(\+([\d\.,]+) XP\)$/, '精华 (+$1 经验值)'],
    [/^Essence \(\+([\d\.,]+) XP\) \[([\d\.,]+)\/([\d\.,]+)\]$/, '精华 (+$1 经验值) [$2/$3]'],
    [/^Damage \+ ([\d\.]+)$/, '伤害 +$1'],
    [/^HP \+([\d\.,]+)$/, '生命值 +$1'],
    [/^Regen ([\d\.,]+)\/sec$/, '回复 $1/秒'],
    [/^Plane ([\d\.,]+)$/, '位面 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Accumulate total Essence ([\d\.,]+)$/, '累积总精华 $1'],
    [/^Reach Floor ([\d\.,]+) this life$/, '这一生到达第 $1 层'],
    [/^Clear Floor ([\d\.,]+)$/, '清理层数 $1'],
    [/^Effect: \+([\d\.,]+) Physical Damage$/, '效果: +$1 物理伤害'],
    [/^Effect: \+([\d\.,]+) Armor Pen$/, '效果: +$1 护甲穿透'],
    [/^Effect: \+([\d\.,]+) HP Regen$/, '效果: +$1 生命值回复'],
    [/^Effect: \+([\d\.,]+) Flat Armor$/, '效果: +$1 平装护甲'],
    [/^Effect: \+([\d\.,]+)\% Dodge Chance$/, '效果: +$1% 闪避几率'],
    [/^Effect: \+([\d\.,]+)\% Crit Damage$/, '效果: +$1% 暴击伤害'],
    [/^Effect: \+([\d\.,]+)\% Crit Chance$/, '效果: +$1% 暴击几率'],
    [/^Effect: \+([\d\.,]+)\% Hit Chance$/, '效果: +$1% 命中几率'],
    [/^Effect: \-([\d\.,]+)\% Attack Interval$/, '效果: -$1% 攻击间隔'],
    [/^([\d\.,]+)\/([\d\.,]+) complete$/, '$1\/$2 完成'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^ \— ([\d\.,]+)\/([\d\.,]+) Stage$/, ' - $1 \/ $2 关卡'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);