/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "Combat Log": "战斗日志",
    "Dao (Locked)": "道 (未解锁)",
    "Stat Allocation": "属性分配",
    "Resume": "返回",
    "Tutorial • Floor": "教程 • 层数",
    "Floor": "层数",
    "Continue": "继续",
    "Patch Notes - v": "更新日志 - v",
    "Reset Save": "重置存档",
    "Plane (???)": "计划 (???)",
    "Allocate:": "分配:",
    "Awakening the Dao…": "觉醒之道...",
    "Consolidate Insights": "巩固洞察力",
    "Auto progression": "自动推进",
    "Fixes": "修复",
    "Highlights": "高亮",
    "HP": "生命值",
    "Idle Xanxia v": "放置仙侠 v",
    "Improved stat descriptions": "改进属性描述",
    "Current Path": "当前路径",
    "Offline Gains": "离线收益",
    "Precision": "精准",
    "The Dao never sleeps, neither do you.": "道永不停息，你亦是如此。",
    "The Path of the Immortal": "不朽之路",
    "Up Next": "Up Next",
    "Vitality": "活力",
    "Aspect Awakened": "天赋觉醒",
    "You have accumulated Insight, keep pushing yourself!": "你已经积累了洞察力，继续努力前行吧！",
    "You have defeated": "你击败了",
    "none": "无",
    "essences:": "精华:",
    "Inner Self": "内在自我",
    "Meditate": "冥想",
    "Might": "实力",
    "Slime": "史莱姆",
    "Rebirth (???)": "重生 (???)",
    "Not consolidated:": "未巩固:",
    "Resilience": "韧性",
    "Swiftness": "敏捷",
    "to the next breakthrough": "迈向下一个突破",
    "No battles were credited.": "暂无战斗记录。",
    "Insights - The understanding you gain through battle and reflection. Consolidate Insights to advance your cultivation.": "洞察力 - 你通过战斗和反思获得的理解。将洞察力加以巩固，以促进你的修炼进程。",
    "Insights": "洞察力",
    "First Insight": "第一次洞察",
    "Cultivation Begins": "修炼开始了",
    "Enough. \n\n The essence you have gathered has taken form. \n\n Look inside yourself.": "足够了。\n\n你收集到的精华已经成形。\n\n 请审视自己的内心。",
    "Cultivation": "修炼",
    "Consolidate your insights": "巩固你的洞察",
    "Consolidate": "巩固",
    "Active:": "激活:",
    "Armor": "护甲",
    "Armor Penetration": "护甲穿透",
    "Aspect of the Slime": "史莱姆天赋",
    "A journey of a thousand li begins with a single step. Here I am!": "千里之行，始于足下。我来了！",
    "Attack Interval": "攻击间隔",
    "Explore the forest": "探索森林",
    "Start Your Adventure": "开始你的冒险",
    "Welcome": "欢迎",
    "enemies.": "敌人.",
    "From those battles, you have collected": "从这些战斗中，你收集了",
    "Advance to Floor": "冒险到层数",
    "Pause": "暂停",
    "Chakras": "经脉",
    "Body Foundation": "身体基础",
    "Back to Combat": "返回到战斗",
    "Damage": "伤害",
    "Common": "普通",
    "Rare": "稀有",
    "Legendary": "传说",
    "Uncommon": "罕见",
    "A frog in a well.": "井底之蛙。",
    "A toad wanting to eat swan meat.": "一只蟾蜍想吃天鹅肉。",
    "Cripple your own cultivation and save me some time.": "自毁自己的修炼过程，为我节省些时间。",
    "Do you even know who my father is?": "你到底知不知道我父亲是谁？",
    "Do you ever wonder what swan meat tastes like?": "你有没有想过天鹅肉是什么味道？",
    "Heaven is quiet today.": "今天天堂很安静。",
    "Hmph! Arrogant!": "哼！傲慢！",
    "I, your father, have eaten more salt than you have eaten rice!": "作为你的父亲，我吃的盐比你吃的米饭还多！",
    "I'll give you some face, cripple your own cultivation and crawl away.": "我要让你难堪，毁掉你的修炼过程，然后爬走。",
    "In my youth, servants stronger than you fetched my tea.": "在我年轻的时候，比你更强壮的仆人给我端茶。",
    "Junior, you dare?!": "小弟，你敢吗？",
    "Kowtow three times and I might leave your corpse intact.": "磕头三次，我或许能让你的尸体完好无损。",
    "Seriously though, do you know who my father is? I was abandoned when I was little...": "不过说真的，你知道我父亲是谁吗？我小时候被遗弃了……",
    "Striking a stone with an egg.": "用鸡蛋敲石头。",
    "The gap between us is like heaven and earth.": "我们之间的差距就像天与地。",
    "Wait - that was my last life-saving treasure.": "等等——那是我最后的救命宝物。",
    "You are but a speck of dust dreaming it is a mountain.": "你不过是一粒尘埃，却妄想自己是一座山。",
    "You are courting death!": "你在走向死亡！",
    "You are not qualified to speak in my presence.": "你没有资格在我面前说话。",
    "You cultivate like a blind man painting.": "你修炼得像个盲人作画。",
    "You have eyes but cannot see Mt. Tai.": "你有眼睛却看不到泰山。",
    "You overestimate yourself.": "你自视过高。",
    "Your cultivation is shallow, but your arrogance is deep.": "你的修为浅薄，但你的傲慢却很深。",
    "Your existence offends my eyes.": "你的存在冒犯了我的眼睛。",
    "Your family tree should have ended at the root.": "你的家族谱应该在根部就终止了。",
    "Miss": "未命中",
    "Awakened (": "觉醒 (",
    "Effects": "效果",
    "Dodge": "闪避",
    "Equipped (": "已装备 (",
    "Tier": "层级",
    "Regen per second": "回复每秒",
    "Loadingâ€¦": "加载中¦",
    "In Progress (": "进行中 (",
    "Hit Point": "命中点",
    "Hit Chance": "命中率",
    "Foundation": "基础",
    "Essence Assimilation": "精华同化",
    "Damage Mitigation": "伤害减免",
    "Awakened Aspects": "觉醒天赋",
    "Critical Chance": "暴击几率",
    "All awakened Aspects are equipped.": "所有觉醒的天赋都已装备。",
    "Confirm Reset": "确认重置",
    "Are you sure you want to reset the game, All progress will be lost": "你确定要重置游戏吗？届时所有进度都将丢失。",
    "A Master's Warning": "一位大师的告诫",
    "Return to the Woods": "返回到森林",
    "Temper yourself": "磨练自己",
    "You're not ready for this beast yet.\n\n Go back in the woods, find an enemy you want to learn from and use my amulet to collect their essence.": "你目前还不具备面对这个怪物的条件。\n\n回到森林里去吧，找一个你想要学习的敌人，然后用我的护身符来收集他们的灵魂精华。",
    "Bunnycorn": "玉米兔",
    "Wolf": "狼",
    "None.": "无.",
    "Equipped Aspects": "已装备天赋",
    "Active Effects": "激活效果",
    "Aspects": "天赋",
    "Elite": "精英",
    "Aspect of the Forest Wolf": "森林狼天赋",
    "Aspects In Progress": "进行中的天赋",
    "No Aspects equipped.": "暂未装备天赋。",
    "Attribute Cultivation": "属性培养",
    "Aspect": "天赋",
    "Awakened": "已觉醒",
    "Assimilation": "吸收",
    "Body": "身体",
    "Dao (locked)": "道 (未解锁)",
    "Equipped": "已装备",
    "MAX": "最大",
    "In Progress": "进行中",
    "Forest Wolf": "森林狼",
    "Acupoint Awakening": "穴位激活",
    "Blood Refinement": "血液净化",
    "Bone Forging": "骨骼锻造",
    "Chakra Purification": "脉轮净化",
    "Cultivation Realm": "修炼境界",
    "Flesh Remodeling": "肉体重塑",
    "Inner Foundation": "内在根基",
    "Jade Body": "玉质身躯",
    "Major Realm Completion": "主要境界达成",
    "Marrow Cleansing": "骨髓净化",
    "Mortal Realm": "凡人境界",
    "Skin Tempering": "皮肤淬炼",
    "Tendon Strengthening": "肌腱强化",
    "Your blows find both flesh and weakness.": "你的攻击既能击中肉体，也能击中弱点。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Mortal Realm • Skin Tempering — 1st Stage": "凡人界 • 皮肤强化 — 第 1 阶段",
    "Mortal Realm • Skin Tempering — 2nd Stage": "凡人界 • 皮肤强化 — 第 2 阶段",
    "Mortal Realm • Skin Tempering — 3rd Stage": "凡人界 • 皮肤强化 — 第 3 阶段",
    "Mortal Realm • Flesh Remodeling — 1st Stage": "凡人界 • 肉体重塑 — 第 1 阶段",
    "Mortal Realm • Flesh Remodeling — 2nd Stage": "凡人界 • 肉体重塑 — 第 2 阶段",
    "Mortal Realm • Flesh Remodeling — 3rd Stage": "凡人界 • 肉体重塑 — 第 3 阶段",
    "Mortal Realm • Tendon Strengthening — 1st Stage": "凡人界 • 肌腱强化 — 第 1 阶段",
    "Mortal Realm • Tendon Strengthening — 2nd Stage": "凡人界 • 肌腱强化 — 第 2 阶段",
    "Mortal Realm • Tendon Strengthening — 3rd Stage": "凡人界 • 肌腱强化 — 第 3 阶段",
    "Mortal Realm • Bone Forging — 1st Stage": "凡人界 • 锻骨 — 第 1 阶段",
    "Mortal Realm • Bone Forging — 2nd Stage": "凡人界 • 锻骨 — 第 2 阶段",
    "Mortal Realm • Bone Forging — 3rd Stage": "凡人界 • 锻骨 — 第 3 阶段",
    "Mortal Realm • Blood Refinement — 1st Stage": "凡人界 • 血脉淬炼 — 第 1 阶段",
    "Mortal Realm • Blood Refinement — 2nd Stage": "凡人界 • 血脉淬炼 — 第 2 阶段",
    "Mortal Realm • Blood Refinement — 3rd Stage": "凡人界 • 血脉淬炼 — 第 3 阶段",
    "Mortal Realm • Organ Fortification — 1st Stage": "凡人界 • 器官强化 — 第 1 阶段",
    "Mortal Realm • Organ Fortification — 2nd Stage": "凡人界 • 器官强化 — 第 2 阶段",
    "Mortal Realm • Organ Fortification — 3rd Stage": "凡人界 • 器官强化 — 第 3 阶段",
    "Mortal Realm - Organ Fortification - 1st Stage": "凡人界 - 器官强化 — 第 1 阶段",
    "Mortal Realm - Organ Fortification — 2nd Stage": "凡人界 - 器官强化 — 第 2 阶段",
    "Mortal Realm - Organ Fortification — 3rd Stage": "凡人界 - 器官强化 — 第 3 阶段",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "✕": "✕",
    "(*)": "(*)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "@": "@",
    "^": "^",
    "&": "&",
    "%": "%",
    "--": "--",
    "=": "=",
    "?": "?",
    "!": "!",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Floor ": "层数 ",
    "Explore the forest: ": "探索森林: ",
    "Organ Fortification": "器官强化",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(([\d\.]+), ([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^\@keyframes(.+)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Mortal Realm • Skin Tempering \— (.+)th Stage$/, '凡人界 • 皮肤强化 — 第 $1 阶段'],
    [/^Mortal Realm • Flesh Remodeling \— (.+)th Stage$/, '凡人界 • 肉体重塑 — 第 $1 阶段'],
    [/^Mortal Realm • Tendon Strengthening \— (.+)th Stage$/, '凡人界 • 肌腱强化 — 第 $1 阶段'],
    [/^Mortal Realm • Bone Forging \— (.+)th Stage$/, '凡人界 • 锻骨 — 第 $1 阶段'],
    [/^Mortal Realm • Blood Refinement \— (.+)th Stage$/, '凡人界 • 血脉淬炼 — 第 $1 阶段'],
    [/^Mortal Realm • Organ Fortification \— (.+)th Stage$/, '凡人界 • 器官强化 — 第 $1 阶段'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.]+)\/sec$/, '+$1/秒'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) HP Regen$/, '+$1 生命值回复'],
    [/^\+([\d\.,]+) Physical Damage$/, '+$1 物理伤害'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Defeated Wolf \(\+([\d\.,]+) XP\)$/, '击败 狼 (+$1 经验值)'],
    [/^Defeated Bunnycorn \(\+([\d\.,]+) XP\)$/, '击败 玉米兔 (+$1 经验值)'],
    [/^Defeated Slime \(\+([\d\.,]+) XP\)$/, '击败 史莱姆 (+$1 经验值)'],
    [/^Essence \(\+([\d\.,]+) XP\)$/, '精华 (+$1 经验值)'],
    [/^Essence \(\+([\d\.,]+) XP\) \[([\d\.,]+)\/([\d\.,]+)\]$/, '精华 (+$1 经验值) [$2/$3]'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Effect: \+([\d\.,]+) Physical Damage$/, '效果: +$1 物理伤害'],
    [/^Effect: \+([\d\.,]+) HP Regen$/, '效果: +$1 生命值回复'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^ \— ([\d\.,]+)\/([\d\.,]+) Stage$/, ' - $1 \/ $2 关卡'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);